- packages/context/README.md
- packages/context/src/api/apiServices.ts
- packages/context/src/notification/NotificationProvider.tsx
- packages/context/src/notification/index.ts
Set session id to api request headers
> feat: add notification provider

- packages/context/src/authentication/AuthenticationContextProvider.tsx
When log out successfully, users will be redirected to the logout screen.
Users will be redirected to the last page before they logged out when they log in again.
> feat: redirect to logout screen

- packages/plugin/src/generators/app/templates/src/widgets/SampleWidget/WidgetProperties.json
- widgetschema.json
Add schema validation and IntelliSense for WidgetProperties.json
> feat: add widget schema

- packages/context/src/objects/objects.ts
Reverts Evoke-Platform/evoke-sdk#530
Should not change type names.
> Revert "feat: add table view layout type"

- packages/context/src/objects/objects.ts
Needed for making single select properties into radio buttons and sorting them according to their configuration/alphabetically
> feat: add choicesDisplay and sortBy options for singleSelect styling

- packages/context/src/objects/objects.ts
This will stop the Configuration pipeline from failing
> feat: add radioButton option to ActionInput displayOption

- packages/context/src/objects/objects.ts
This adds the information needed for sorting to the DropdownViewLayout model.
Refs: CDR-2129
> feat: add DropdownViewLayoutSort type and add sort to DropdownViewLayout

- packages/context/src/objects/objects.ts
This further defines the form types so that they align with the api specification.
> feat: further define form types

- packages/context/src/objects/objects.ts
operator should be `'eq' | 'ne'`
Refs: CDR-2146
> fix: amend VisibilityCondition opeartor to correct value

- packages/context/src/objects/objects.ts
> feat: add EvokeForm, InputField, and ReadonlyField types, and expand Obj and FormEntry

- packages/context/src/objects/objects.ts
> feat: add "nonStrictEnum" to property and input model

- packages/context/src/objects/objects.ts
> feat: update choicesDisplay type values

- packages/context/src/objects/objects.ts
> fix: update display configuration type

- packages/context/src/objects/objects.ts
> feat: add strictlyTrue flag for boolean property

- packages/context/src/objects/objects.ts
> feat: introduce submit label configuration to EvokeForm

- packages/context/src/objects/objects.ts
> feat: add default form id to action

- packages/context/src/authentication/AuthenticationContextProvider.tsx
Track the page so if the user logs back in, they will be sent back to the same page.
> feat(context): track current page on log out

- packages/context/src/objects/objects.ts
> fix: add null to optional types

- widgetschema.json
Adding the new betaRelease flag to the schema for widget properties
> feat(schema): add betaRelease boolean property to widget schema

- packages/context/src/objects/objects.ts
> feat: add allowedFileExtensions and maxSizeInKB to DocumentValidation type

- packages/context/src/objects/objects.ts
> fix: update ActionInput validation

- packages/context/src/authentication/AuthenticationContextProvider.tsx
There seems to be a lack of context syncing in certain edge cases. For now allow sharing the oidc instance, similar to msal, to enforce context sharing.
> fix(CDR-2403): add option to pass oidc instance to AuthenticationContext

- packages/context/src/api/apiServices.ts
> feat(api): add File type to Data type
